ALTER TABLE "TruckRepair"
  ADD COLUMN IF NOT EXISTS "quantity" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "toolId" INTEGER NULL;

ALTER TABLE "TruckRepair"
  ADD CONSTRAINT "TruckRepair_toolId_fkey"
  FOREIGN KEY ("toolId") REFERENCES "Tool" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Truck"
  ADD COLUMN IF NOT EXISTS "insuranceExpiry" TIMESTAMPTZ NULL;
