ALTER TABLE "Invoice"
  ADD COLUMN IF NOT EXISTS "jobSiteId" INTEGER NULL,
  ADD CONSTRAINT "Invoice_jobSiteId_fkey" FOREIGN KEY ("jobSiteId") REFERENCES "JobSite" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
